// `.env.ts` is generated by the `npm run env` command

export const environment = {
  production: true,
  version: '1.0.2',
  serverUrl: '/api/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  APIserverUrl: '',
  cookieDomain: 'localhost',
  userSessionTimeout: 900 // in seconds
};
