// `.env.ts` is generated by the `npm run env` command
import env from './.env';

export const environment = {
  production: true,
  // version: env.npm_package_version,
  // serverUrl: 'https://api.chucknorris.io',
  // defaultLanguage: 'en-US',
  // supportedLanguages: ['en-US', 'fr-FR']
  // environment.ts
  version: env.npm_package_version,
  serverUrl: 'http://13.233.68.200:8000/api/',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'fr-FR'],
  APIserverUrl: '',
  cookieDomain: 'localhost',
  userSessionTimeout: 900 // in seconds
};
