export enum UserPermission {
  USE_AGENT_SEARCH_FUNCTIONALITY = 'can_use_agent_search_functionality',
  VIEW_PROVIDER_CONTACT_DETAILS = 'can_view_provider_contact_details',
  EDIT_SELF_PROFILE = 'can_edit_self_profile',
  REGISTER_NEW_USER = 'can_register_new_user',
  VIEW_CONSUMER_PROFILE = 'can_view_consumer_profile',
  EDIT_CONSUMER_PROFILE = 'can_edit_consumer_profile',
  VIEW_PROVIDER_PROFILE = 'can_view_provider_profile',
  EDIT_PROVIDER_PROFILE = 'can_edit_provider_profile',
  VIEW_PROVIDERS_PRIVATE_PROFILE = 'can_view_providers_private_profile',
  EDIT_PROVIDERS_PRIVATE_PROFILE = 'can_edit_providers_private_profile',
  VIEW_PROVIDERS_PUBLIC_PROFILE = 'can_view_providers_public_profile',
  EDIT_PROVIDERS_PUBLIC_PROFILE = 'can_edit_providers_public_profile',
  CREATE_PROVIDER_PROFILE = 'can_create_provider_profile',
  VIEW_NOTIFICATIONS = 'can_view_notifications',
  VIEW_PROVIDER_PROFILE_CHANGE_REQUESTS = 'can_view_provider_profile_change_requests',
  VIEW_ALL_PROVIDER_PROFILE_CHANGE_REQUESTS = 'can_view_all_provider_profile_change_requests',
  EDIT_PROVIDER_PROFILE_CHANGE_REQUESTS_STATUS = 'can_edit_provider_profile_change_request_status',
  EDIT_ALL_PROVIDER_PROFILE_CHANGE_REQUESTS_STATUS = 'can_edit_all_provider_profile_change_request_status',
  DO_AGENT_OPERATIONS = 'can_do_agent_operations',
  REQUEST_NEW_ROLE = 'can_request_new_role',
  DO_PROVIDER_OPERATIONS = 'can_do_provider_operations',
  CREATE_PROVIDER_PROFILE_CHANGE_REQUESTS_AS_AGENT = 'can_create_provider_profile_change_requests_as_agent'
}
